---
title: "Virtual Seminars"
description: |
  Open talks for everyone at any time
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## OPP Virtual seminars 

Coordinated by [Dr. Benjamin Schwessinger](https://twitter.com/schwessinger), the Virtual Seminars (aka science webinars) are a venue for delivering scientific talks of general interest to a plant pathology audience. Anyone is welcome to contribute a seminar. If you are interested, [please answer a few questions for approval](https://docs.google.com/forms/d/e/1FAIpQLSdCBzRJRzSVnx4J-sIaeAfpQvbSGHCjyINnIT-tqOKLk3wPQA/viewform?usp=send_form).

-   The seminars are pre-approved and disseminated widely via [Twitter](https://twitter.com/OpenPlantPath).

-   It is live broadcast via Zoom at a date & time of the speaker's convenience.

-   The speaker is available to answer questions from the audience after the seminar (e.g. up to 1 hour) either within the Zoom chat and/or on the OPP Slack channel for webinars.

-   The live event will be recorded and uploaded to our [YouTube channel](https://www.youtube.com/channel/UCo-1ijIA_nECqzwzeW2X9RA).

-   The video file and all associated materials (slides, chat texts, codes, etc.) will be made freely accessible under the [CC BY](https://creativecommons.org/licenses/) license through OSF with a DOI provided for each the materials presented.

- Click [here](index.html#category:Virtual_seminars) to retrieve the list of all Virtual seminars hosted by Open Plant Pathology

## CCH-USQ Seminar Series 

In addition to our Virtual seminars promoted by OPP, we've hosted distributed in our YouTube Channel the recordings of talks given at the Seminar Series of the Center for Crop Health, University of Southern Queensland (CCH-USQ). 

- Click [here](index.html#category:CCH-USQ_Seminars) to retrieve the list of all CCH-USQ seminars.
