---
title: "Who we are"
description: |
  Get to know who has worked to make this possible
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

OpenPlantPathology is a not for-profit initiative founded in January 2018 by [Emerson Del Ponte](emersondelponte.netlify.app) and [Adam Sparks](https://adamhsparks.com/) to facilitate communication among computational plant pathologists and promote open science and reproducible research practices in plant pathology. Of course, this would not be possible without the support from several colleagues who helped spread the initiative and the culture of open science. Currently, our team is composed of the following leaders.

[**Adam Sparks**](https://www.adamhsparks.com/)\
Founder. Webmaster\
Senior Research Scientist, Bioeconomic Modeller\
Department of Primary Industries and Regional Development (DPIRD), Western Australia, Australia

[**Emerson Del Ponte**](https://emersondelponte.netlify.app/)\
Founder. Webdesigner\
Plant Pathologist\
Universidade Federal de Viçosa, Brazil

[**Lisa Rothmann**](https://twitter.com/LandbouLisa)\
Sci-comm Editor\
Plant Pathologist\
University of the Free State, Bloemfontein South Africa

[**Fernando García-Bastidas**](https://twitter.com/Ferchucky)\
Digital media Editor\
Plant Pathologist\
Keygen, Netherlands

[**Benjamin Schwessinger**](https://twitter.com/schwessinger)\
Virtual Seminars Coordinator\
Plant Pathologist\
Australian National University, Canberra, Australia

[**Zhian Kamvar**](https://twitter.com/ZKamvar)\
Editor for Reproducibility\
Plant Pathologist\
The Carpentries, USA

[**Susann Auer**](https://twitter.com/SusannAuer)\
Editor for Reproducibility\
Plant Pathologist\
Technische Universität Dresden, Germany
