---
title: "Johanna Westerdijk: curating culture in the discipline of plant pathology"
description: |
  In this second #OPPToons, a tribute to a pioneering and inspiring woman in plant pathology, Prof. Johanna Westerdijk (1883-1961), the first female Professor in the Netherlands, from the University of Utrecht.
  
  
author:
  - name: Lisa Rothmann
    url: https://twitter.com/LandbouLisa
  - name: Fernando García-Bastidas
    url: https://twitter.com/Ferchucky
date: 05-23-2021
output:
  distill::distill_article:
    self_contained: false
preview: Westerdijk-preview.png
categories: 
  - OPPToons
---

As botanical and agricultural sciences were firmly established from the mid-19th century, plant pathology also emerged and matured as a discipline of its own.
Formal academic departments and societies were being formed to develop a united front for the budding field of plant pathology.
The Royal Netherlands Phytopathology Society was the first organised society to establish in 1891, driven by Prof Hugo de Vries, Prof Jacob Eriksson and Dr Jan Ritzema Bos, and is recognised as the oldest society.

The foundation of a phytopathology institute in the Netherlands came with challenges, political and financial, however after 3 years, through the private support of an Amersterdam trader, the Willie Commelin Scholten (WCS) Phytopathology Laboratory was established.
In 1906, Dr Johanna Westerdijk, 23-years old and a recently graduated Swiss botanist, accepted the position as the successor to Ritzema Bos (the director of the Institute for Phytopathology, in Wageningen, 1905) as the director of the WCS laboratory.

![Cartoon of Johanna Westerdijk inspecting samples in laboratory bench. Caption: Johanna Westerdijk (1883-1961) was an energetic, people-oriented, intelligent and fundamental science-focused oriented woman and researcher. It is not surprise that within 11 years, Dr. Westerdijk was promoted at the University of Utrecht to Prof. of Phytopathology - the first female Professor in the Netherlands](Westerdijk.jpg)

At the beginning of her tenure, Dr Westerdijk was requested to take care of Frits Went's fungal cultures, initiating the Central Bureau of Fungal Cultures (Centraal Bureau voor Schimmelcultures, CBS), in 1907.
As an energetic, people-orientated, intelligent and fundamental science-focused woman and researcher, it is no surprise that within 11 years, Dr Westerdijk was promoted at the University of Utrecht to professor of phytopathology - the first female professor in the Netherlands.

The growth under Westerdijk, required a joint venture between the University of Amsterdam and the University of Utrecht, to be initiated, moving the WCS laboratory and the CBS to Baarn, in 1920.
The CSB was initiated with 50 cultures, deposited by Went, but at the time of Westerdijks retirement, almost 9000 cultures were curated by the CBS, now at the Utrecht Science Park (directed by Prof. Pedro Crous).
To honour Johanna Westerdijk, the collection is now known as the Westerdijk Fungal Biodiversity Institute.
During her role as director and professor, Westerdijk tackled problems (and low expectations from her male peers) with a headstrong and practical approach, diagnosing and providing extension reports for damping-off in sugar beets, caused by Phoma betea.
However, Westerdijk was so fascinated by the Dutch elm disease, after it was first noticed in 1919, that she decided to focus her research with intention on this single disease.

As Westerdijk had great people skills she managed to encourage almost 1000 municipalities to invest in research to prevent elms in their districts from being infected.
Not only could she gather funds, but people, Westerdijk supported her female peers and eagerly collaborated with them.
Working with Barendina Spierenburg and Marie Beatrice Schwarz, they attempted to prove the causal organism of this devastating epidemic.
Perhaps, to the dismay of many senior male researchers, Westerdijk and her team, as well as a new female graduate student, Christine Buisman (unfortunately, passing away in 1936), managed to prove the Ophiostoma novo-ulmi (then Graphium ulmi) was causing Dutch elm disease.
Female students and staff under the supervision of Westerdijk continued to research applied strategies to control this wilting disease of elm, through chemotherapy (which was not pursued in-depth due to phytotoxicity) and a successful breeding program - of which trees are still being enjoyed today in the Netherlands.

In 1945 Westerdijk was the president of the Royal Netherlands Phytopathology Society and continued on as a phytopathologist of international calibre, studying in Switzerland and Germany, visiting Indonesia, the United States and forming close collaborations and friendships with South African researchers.
With the retirement of Westerdijk in 1952, she handed over the reins to her successor, Prof. Louise Kerling.
Her passing in 1961, left a legacy for plant pathology not only in the Netherlands but abroad too.
Described as a joyful and spirited woman, Westerdijk lived by the motto: 'For fine minds, the art is, to mix work and parties', 'Werken en feesten vormt schone geesten'\_, she managed to break glass ceilings and build beautiful bridges, so we may all benefit from her and her team's contributions.
The above is a blurb inspired by an article to commemorate Johanna Westerdijk in the European Journal of Plant Pathology (2019) by [Boonekamp et al. (2019)](https://link.springer.com/content/pdf/10.1007/s10658-019-01670-w.pdf).
