---
title: "Open Plant Pathology - Member Directory"
output:
  flexdashboard::flex_dashboard:
    theme: flatly
    logo: opp-logo.png
    social: [ "twitter", "facebook" ]
    navbar:
      - { title: "<i class='fa fa-arrow-circle-left' aria-hidden='true'></i> Homepage", href: "https://www.openplantpathology.org/", align: right }
      - { title: "<i class='fa fa-github' aria-hidden='true'></i> GitHub", href: "https://github.com/openplantpathology/OpenPlantPathology/tree/master/public/directory", align: right }

---

```{r echo=FALSE}
knitr::asis_output(htmltools::htmlPreserve("
<link rel='stylesheet' href='https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css'>
"))

`%notin%` <- function(x, table) {
  # Same as !(x %in% table)
  match(x, table, nomatch = 0L) == 0L
}
```


```{r include=FALSE}
# load encrypted API key
GOOGLE_API_KEY <- Sys.getenv("GOOGLE_API_KEY")

# read data from Google Sheets
library(gsheet)

members <-
  gsheet2tbl(
    "https://docs.google.com/spreadsheets/d/1VHGz8oWia5qvleUozznCIgd9bD85XoXm1NWmE6t8nzo/edit?usp=sharing"
  )

# prepare the dataset for table, plot and map
library(tidyverse)
members <-
  members %>%
  unite(geo,
        location,
        state,
        country,
        remove = FALSE,
        sep = ", ") %>%
  replace_na(
    list(
      domain1 = "",
      domain2 = "",
      middle_name = "",
      homepage = "",
      twitter = "",
      github = "",
      orcid = "",
      researchgate = "",
      googlescholar = ""
    )
  ) %>%
  unite(domain, domain1, domain2, remove = TRUE, sep = ", ") %>%
  unite(name, first_name, middle_name, last_name, sep = " ") %>%
  select(
    name,
    role,
    domain,
    institution,
    location,
    state,
    country,
    homepage,
    twitter,
    github,
    orcid,
    researchgate,
    googlescholar
  )

members$institution[is.na(members$institution)] <- ""

# geocode locations
library(googleway)

set_key("GOOGLE_API_KEY")
# create a vector of locations to geocode
locations <-
  as.list(
    paste(
      members$institution,
      members$location,
      members$state,
      members$country,
      sep = ", "
    )
  )
names(locations) <- members$name

# geocode locations using googleway using all location vars
locations <- lapply(locations, google_geocode, key = GOOGLE_API_KEY)

# unnest the lists and extract only the necessary lat/lng values
# some return more than set of coordinates, take only first row of each
x <- vector("list", length = length(locations))
for (i in 1:length(locations)) {
  if (is.null(locations[[i]]$results$geometry$location[1,])) {
    x[[i]] <- data.frame(lat = NA, lng = NA)
  } else
    x[[i]] <- locations[[i]]$results$geometry$location[1,]
}

x <- bind_rows(x)

# join locations with members list
members <- data.frame(members, x)
```

Column {data-width=700px}
----------------------------------

### <i class="fa fa-table" aria-hidden="true"></i> Member information

```{r echo=FALSE}

# dynamic table using DT package

library(DT)
members_table <- members %>%
  select(name,
         role,
         domain,
         institution,
         country,
         homepage,
         twitter,
         github,
         orcid,
         researchgate,
         googlescholar
  )

# construct external links and icons to go with names
# website links
members_table$homepage2 <-
  paste0(
    "<a href = '",
    members_table$homepage,
    "'><i class='fa fa-link aria-hidden=TRUE', style='margin:4px;'></i></a>"
  )
members_table$homepage2[members_table$homepage == ""] <- ""

# researchgate links
members_table$researchgate2 <-
  paste0(
    "<a href = '",
    members_table$researchgate,
    "'><i class='ai ai-researchgate aria-hidden=TRUE; style='color:#21CBBB;margin:4px'></i></a>"
  )
members_table$researchgate2[members_table$researchgate == ""] <- ""

# orcid links

members_table$orcid2 <-
  paste0(
    "<a href = '",
    members_table$orcid,
    "'><i class='ai ai-orcid', style='color:#A6CE39;margin:4px;'></i></a>"
  )
members_table$orcid2[is.na(members_table$orcid)] <- ""

# twitter links
members_table$twitter2 <-
  paste0(
    "<a href = '",
    members_table$twitter,
    "'><i class='fa fa-twitter', style='color:#1da1f2;margin:4px;'></i></a>"
  )
members_table$twitter2[members_table$twitter == ""] <- ""

# github links
members_table$github2 <-
  paste0(
    "<a href = '",
    members_table$github,
    "'><i class='fa fa-github'; style='color:#000000;margin:4px;'></i></a>"
  )
members_table$github2[members_table$github == ""] <- ""

# ResearchGate links
members_table$researchgate2 <-
  paste0(
    "<a href = '",
    members_table$researchgate,
    "'><i class='ai ai-researchgate'; style='color:#21CBbb;margin:4px;'></i></a>"
  )
members_table$researchgate2[members_table$researchgate == ""] <- ""

# Google Scholar links
members_table$googlescholar2 <-
  paste0(
    "<a href = '",
    members_table$googlescholar,
    "'><i class='ai ai-google-scholar'; style='color:#404CC9;margin:4px;'></i></a>"
  )
members_table$googlescholar2[members_table$googlescholar == ""] <- ""

# add links to `names` column
members_table$name <- 
  paste0(
    members_table$name,
    "<br>",
    members_table$homepage2,
    members_table$orcid2,
    members_table$twitter2,
    members_table$github2,
    members_table$googlescholar2,
    members_table$researchgate2
  )

# drop extra columns now that the info is in `name`
members_table <-
  select(members_table,
    -c(
      "homepage",
      "homepage2",
      "twitter",
      "twitter2",
      "github",
      "github2",
      "googlescholar2",
      "googlescholar",
      "researchgate"
    )
  )

datatable(
  members_table,
  escape = FALSE,
  rownames = FALSE,
  colnames = c(
    "Member",
    "Role",
    "Domain(s)",
    "Institution",
    "Country"
  ),
  class = "cell-border stripe",
  options = list(
    order = list(list(0, "asc")),
    # order by first variable
    autoWidth = TRUE,
    columnDefs = list(list(width = "120px", targets = c(0))),
    scroller = TRUE,
    pageLength = 50,
    fontSize = 12,
    lengthMenu = c(50, 100, 200)
  )
) %>%
  formatStyle(
    c(
      "name",
      "role",
      "domain",
      "institution",
      "country"
    ),
    fontSize = "90%")
```


Column {}
----------------------------------

###  <i class="fa fa-map" aria-hidden="true"></i> Global map


```{r echo=FALSE}
library(leaflet)

members <- na.omit(members)

pal <-
  colorFactor(c("#339933", "steelblue"),
              domain = c("Leadership", "Member"))

getColor <- function(members) {
  lapply(members$role, function(role) {
    if (role == "Leadership") {
      "green"
    } else if (role == "Member") {
      "blue"
    }
  })
}
icons <- awesomeIcons(
  icon = "user-o",
  iconColor = "black",
  library = "fa",
  squareMarker = TRUE,
  markerColor = getColor(members)
)

map <- leaflet(members) %>%
  setView(lng = 0, lat = 5, zoom = 1) %>%
  addTiles(urlTemplate = "https://mts1.google.com/vt/lyrs=r&hl=en&src=app&x={x}&y={y}&z={z}&s=G", attribution = "Google") %>%
  addAwesomeMarkers(
    ~lng,
    ~lat,
    icon = icons,
    label = paste(members$name, "- click for details"),
    popup = paste("<b>", members$name, "</b><br>",
                  members$institution, "<br>",
                  members$location, ",", members$country, "<br>",
                  "Domain(s):", members$domain, "<br>"),
    clusterOptions = markerClusterOptions(),
  ) %>%
  addLegend(
    "bottomleft",
    pal = pal,
    values = ~role,
    title = "Role",
    opacity = 1
  ) %>%
  addEasyButton(easyButton(
    icon = "fa-globe",
    title = "Back to initial view",
    onClick = JS("function(btn, map){ map.setZoom(1); }")
  ))
map
```


### <i class="fa fa-bar-chart" aria-hidden="true"></i> Members by knowledge domain


```{r echo=FALSE}
library(plotly)

# sort domains so that we don't have duplicates in different orders
members$domain <- sapply(strsplit(as.character(members$domain), ", "),
                         function(x) paste(x, collapse = " &\n"))

p <- members %>% 
  ggplot(aes(domain, fill = domain)) +
  geom_bar() +
  scale_fill_hue() +
  theme_minimal() +
  theme(legend.position = "right", axis.text.x = element_blank()) +
  labs(fill = "Domain",
       y = "Number of Members",
       x = "",
       title = "Members acting in up to two domains")
ggplotly(p)
```
