---
title: "OPP Interviews: Sophien Kamoun"
description: |
  In this OPP series we will be interviewing scientists in Plant Pathology or related areas who has embraced open science and contributed knowledge and tools to advance the field. Our first interviewee is Prof. Sophien Kamoun, a senior scientist with the Sainsbury Laboratory, Norwich, UK. Dr. Kamoun is known for his prolific tweeting but, also importantly, for his work with oomycetes, effectors, genomics and evolution. 

author:
  - name: Emerson Del Ponte
    url: https://twitter.com/edelponte
date: 11-13-2018
output:
  distill::distill_article:
    self_contained: false
preview: interview-kamoun.png
categories: 
  - Interviews
---


In this OPP series we will be interviewing scientists in Plant Pathology or related areas who has embraced open science and contributed knowledge and tools to advance the field. 

Prof. [Sophien Kamoun](http://www.tsl.ac.uk/staff/sophien-kamoun/), a senior scientist with the Sainsbury Laboratory, Norwich, UK. Dr. Kamoun is known for his prolific [Tweeting](https://twitter.com/kamounlab?lang=en) but, also importantly, for his work with oomycetes [#notafungus](https://twitter.com/hashtag/notafungus), [effectors, genomics and evolution](http://kamounlab.tumblr.com/). 

Prof. Kamoun is well recognized for his efforts to champion data sharing and other open science practices. Recently he was one of the leading scientists who founded [Open Wheat Blast](http://s620715531.websitehome.co.uk/owb/), an initiative with the main goal of providing genomic data and analysis related to wheat blast with open access. The collaborative efforts by several teams allowed to rapidly confirm the source of wheat blast in Bangladesh in early 2016. It is a great pleasure to have Prof. Kamoun as an OPP member and answering a few questions about open science.
<br><br> 

### You have a strong presence in social media, together with other prominent plant pathologists, advocating for more open and transparent science and data sharing. Tell us a bit about your background and when you realized that open science and data sharing were important to furthering science

I think I have always been tuned to new technologies and tools. I'm also aware of the importance of science communication and networking. Therefore, it's perhaps no surprise that I quickly became hooked to Twitter and related social media tools such as[ Scoop.it](https://www.scoop.it/t/mpmi). Twitter has become an integral part of my daily routine. I use it primarily[ to broadcast, gather new information and interact with a wide range of people beyond my immediate colleagues](https://www.slideshare.net/SophienKamoun/sophien-twitter-2014). I love that incessant flow of information we get through Twitter. In some ways, I'm addicted to knowledge and social interactions, and Twitter is my drug.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Q: What inspires you about your job? A: Knowledge and people. <a href="https://t.co/G9ztJsw8Jx">https://t.co/G9ztJsw8Jx</a></p>&mdash; Sophien Kamoun (@KamounLab) <a href="https://twitter.com/KamounLab/status/888474137081118721?ref_src=twsrc%5Etfw">July 21, 2017</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


I think I first became aware of the open science movement with the first open access journals. It must have been the PLOS journals around year 2000. The rationale for open science, notably transparency and accountability, seemed evident given that our objective as scientists is to produce robust reproducible science and share it with others. Later, I became interested in open science as applied to genome sequencing of emerging plant pathogens. I still feel that the plant pathology community is too slow in applying the tools of genomics to new plant disease outbreaks.[ Too little, too late](http://kamounlab.dreamhosters.com/pdfs/MicrobiologyToday_2012.pdf).
<br><br>

### How do you compare the overall field of plant pathology to others in relation to the level of adoption of open science practices? Is there any kind of formal education and training that graduate schools/advisors should be more proactive to educate the new generation of scientists, or is this a matter of individual efforts?

I want to start by saying that [OPP](http://www.openplantpathology.org) is an absolutely amazing initiative that stands out from the conservative stance of many of our plant pathologist colleagues. My experience is that plant pathologists tend to be too slow in embracing the cultural changes that are sweeping the biological sciences. For example, a few months ago I participated in a [workshop] (http://kamounlab.dreamhosters.com/storify/RFBellagio_storify.html) on response to new plant disease outbreaks and some participants argued against open science approaches. There was even opposition to the simple concept of sharing data and biomaterial with experts. Remarkably, our biomedical colleagues manage to do just fine. 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Q: What inspires you about your job? A: Knowledge and people. <a href="https://t.co/G9ztJsw8Jx">https://t.co/G9ztJsw8Jx</a></p>&mdash; Sophien Kamoun (@KamounLab) <a href="https://twitter.com/KamounLab/status/888474137081118721?ref_src=twsrc%5Etfw">July 21, 2017</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


Another aspect that is directly relevant to the acceptance of open science is the issue of research evaluation. Many seem reluctant to [embrace preprints](http://kamounlab.tumblr.com/post/163409024195/whats-up-with-preprints-and-why-im-bothering) because they think that this would not count towards their career progression. Thus, I would encourage everyone to look at the San Francisco Declaration on Research Assessment [(DORA)](https://sfdora.org/), urge their institution to sign up and hold their colleagues to these standards of research evaluation. To sum up, yes, we need more education about open science in plant pathology. OPP fills a critical niche.
<br><br>

### You are among several scientists who strongly voice against the current scholarly publishing practices. You have even refused to review and submit articles for some journals because of the publisher. What is your advice for young scientists who expect recognition publishing in Nature/Cell/Science (NCS)  journals?

Indeed, it's well established that scientific publishing is broken at several levels. But the onus shouldn't be on early career scientists to fix the system, although they can create momentum and enable cultural changes by lobbying for DORA principles, embracing preprints and various other open science initiatives. My advice to early career scientists is to be fully aware that [publishing is important](http://kamounlab.tumblr.com/post/121748816600/what-are-world-class-science-outputs). This is our main currency in science. I'm not arguing against that. But to be a successful scientist, it is critical to have a full set of skills. 

I highly recommend checking the [list of competencies] (https://www.nationalpostdoc.org/page/CoreCompetencies) developed by the National Postdoc Association. If you have some weakness, such as writing, speaking, networking etc., you will struggle to have a fulfilling career unless you address them. Focusing on improving weaknesses is more important than strengths. Even in a great orchestra, you only [hear the bad player](https://twitter.com/GeneticsGSA/status/578654502254993408). What saddens me the most is to see early career scientists become obsessed with publishing in glam mags, such as Science and Nature. It's a total fallacy to believe that all you need is a paper in these journals for your career to be made.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The mentality that if I get a CNS paper my career is set is a false narrative these days for most progressive institutions</p>&mdash; Sophien Kamoun (@KamounLab) <a href="https://twitter.com/KamounLab/status/985817138794565632?ref_src=twsrc%5Etfw">April 16, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Of course, a solid publication record [is important](https://twitter.com/KamounLab/status/985816557170364421) but I have seen many prospective faculty candidates falter despite a publication list that includes these glamorous journals. I recall an interviewee for a faculty position who first-authored three (Yes. Three!) Science papers but couldn't articulate a reasonable response to valid questions from the committee. Needless to say, that interviewee didn't get the job.


My advice is spelled out [here](http://kamounlab.tumblr.com/post/121748816600/what-are-world-class-science-outputs). Aim high. But be reasonable. Also, don't lose the plot. Your job is to produce solid science that stands the test of time, not to squeeze through a wishy-washy paper through reviewers and editors. Trust me, the community knows. Flawed papers get scorned even on [Twitter](https://twitter.com/search?q=%23arseniclife&src=typd). Personally, I'm proud that I got my job as Senior Scientist at The Sainsbury Lab without any Science or Nature papers.  At that time, I thought it said a lot about the institution and how they value their scientists. Finally, the current publishing ethos of my lab is described [here](https://twitter.com/KamounLab/status/1020600779424567296).
<br>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I was hired <a href="https://twitter.com/TheSainsburyLab?ref_src=twsrc%5Etfw">@TheSainsburyLab</a> 10 yrs ago without CNS papers. I&#39;ve been on many committees that turned down CNS authors...</p>&mdash; Sophien Kamoun (@KamounLab) <a href="https://twitter.com/KamounLab/status/882602251084115969?ref_src=twsrc%5Etfw">July 5, 2017</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<br><br>

### As a part of your objections to the current publishing practices you strongly support preprints. What advice do you give for getting started with using preprints? 

Preprints are central to the open science philosophy. I really wish to see more preprints in[ bioRxiv](https://www.biorxiv.org/) from the plant path community. This is a tremendous way to get your work out there and share it with others much earlier than is traditionally the case [See ASAPBIO Preprint FAQ] (http://asapbio.org/preprint-info/preprint-faq). It also relieves the stress associated with waiting for reviews and the tedious revision process. After all, the paper is already out there, so what if the final version takes a few more weeks. It's liberating to [post a preprint just when you finish writing up the paper](http://kamounlab.tumblr.com/post/163409024195/whats-up-with-preprints-and-why-im-bothering).

My main advice is to treat the preprint like a regular paper and not to post premature, unpolished drafts. Some may think that it doesn't matter but you will be judged, even subconsciously, by readers who are the colleagues who will formally review your papers and grants. You wouldn't want to display a scrappy poster or give a messy talk at a conference. 


<blockquote class="twitter-tweet"><p lang="en" dir="ltr">My take is that it depends on the discovery. The way to see it is that preprints are part of a continuum from poster to talks to formal papers evaluated by peers. One could also ask whether a poster or talk would constitute priority...</p>&mdash; Sophien Kamoun (@KamounLab) <a href="https://twitter.com/KamounLab/status/1057547861376860160?ref_src=twsrc%5Etfw">October 31, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


To early career scientists, who may not feel confident to post a preprint, do seek input from your mentors, colleagues or even use scientific writing services to improve the draft. My sense is that the younger generation is puzzled by the traditional protracted process of science publishing and [the costs] (https://twitter.com/KamounLab/status/1009718491832872960) associated with it. Preprints are becoming routine in the biological sciences and [the growth of bioRxiv] (http://www.prepubmed.org/monthly_stats/) has been phenomenal. More concrete actions, such as accepting preprints in promotion packages, grant and fellowship applications are accelerating the process. All it would take now is for funding bodies to mandate preprints, which they really should if they truly believe in their open science manifesto.
<br><br>

### What do you see as the most significant outcome from your work as a result of using open science practices?

 One amazing anecdote is that when we went public with the [sequences from the wheat blast] (http://wheatblast.net/) outbreak in Bangladesh], there was only one (ONE!) genome sequence available of a wheat blast isolate. Obviously, we couldn't do much in interpreting the Bangladeshi sequences based on a single genome. However, it turned out that several labs had unpublished genome sequences of wheat blast isolates sitting in their computers. Within days, there was over 20 genome sequences available. That goes to show the importance of sharing data and also coming up with processes where depositing data sets is recognized as a scholarly contribution just like any other activity.

Another aspect that I found enlightening was the poorly appreciated process of live peer-review. This is what happens when you crowdsource analyses, and more than one group gets involved. You get instant validation! In the case of the wheat blast outbreak, we had two independent analyses performed by [Daniel Croll](https://github.com/crolllab/wheat-blast) in Zurich and [Pierre Gladieux] (http://s620715531.websitehome.co.uk/owb/phylogenomic-analyses-reveal-that-the-2016-outbreak-of-wheat-blast-in-bangladesh-is-caused-by-a-south-american-wheat-infecting-lineage-of-magnaporthe-oryzae/) in Montpellier. They both reached the exact same conclusion that the Bangladeshi strains originated from South America. A great example especially given discussions about the [reproducibility crisis](https://en.wikipedia.org/wiki/Replication_crisis).

### Finally, the Open Plant Pathology community welcomes not only pathologists, but anyone who works in the field and wish to stay connected with other researchers to learn and share knowledge and contribute to promote open science and reproducible research. Surely, it does not fit everyone's needs given the focus of OPP on more computational aspects and use of free open source software (FOSS). What are the areas and target audience that you think might benefit most from participating and taking leadership in this community?

**SK**: Open science can impact several areas of plant pathology beyond computational biology. One example would be the reporting of new disease outbreaks and the first response to these outbreaks. Think of how basic the [ProMED-mail platform is](https://www.promedmail.org/). I think this is the only centralized online platform that rapidly reports new plant disease outbreaks. We should have something akin to a global extension platform with plant pathologists openly contributing advice and analyses on how to respond to these outbreaks. It's shocking to me that the most common word on ProMED-mail is "undiagnosed".

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I was hired <a href="https://twitter.com/TheSainsburyLab?ref_src=twsrc%5Etfw">@TheSainsburyLab</a> 10 yrs ago without CNS papers. I&#39;ve been on many committees that turned down CNS authors...</p>&mdash; Sophien Kamoun (@KamounLab) <a href="https://twitter.com/KamounLab/status/882602251084115969?ref_src=twsrc%5Etfw">July 5, 2017</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


I also hope we can reach out more to developing countries and educate scientists about the value of open science. I recommend you interview my colleague[ Tofazzal Islam](https://twitter.com/tofazzalislam), who became a champion of open science following our collaboration on the Bangladeshi wheat blast outbreak. That experience was [revealing to me too](https://plantae.org/taproot-episode-1-season-1-extreme-open-science-and-the-meaning-of-scientific-impact-with-sophien-kamoun/). It showed the power of open science to help build wide-reaching connections and networks that wouldn't otherwise readily happen.

On a related topic, one of the challenges for scientists in developing countries is to produce full-length publications. Open science tools allow intermediate reports to be published for example through platforms like figshare, zenodo etc. These can be viewed as [credited mini-publications](http://s620715531.websitehome.co.uk/owb/data-analysis/). It's a great opportunity for students and scientists in developing countries to communicate their science in increments without the challenge of producing a typical scientific paper.

At the end, the main challenge is education. The standard system of publication and incentives is so ingrained in the current culture that it is challenging to deliver the necessary changes. We should embrace any opportunity to educate plant pathologists about open science no matter the audience, and no matter the platform.


Other relevant links:
 
http://kamounlab.tumblr.com/post/176385835530/the-edge-of-tomorrow-plant-health-in-the-21st
 
http://kamounlab.tumblr.com/post/178573217080/point-of-view-wither-pre-publication-peer-review




