---
title: "The interesting things we find during cotton disease surveillance in Queensland"
description: |
  Cotton is susceptible to many yield-limiting diseases.  To understand the importance and impact of diseases present, disease surveys are conducted early and late season across all cotton growing regions to monitor the distribution and incidence of diseases. The surveys also maintain the surveillance for exotic pathogens. Surveys have been conducted in Queensland for 20 consecutive years. Data provided by annual surveys have shown the relative importance of each of the diseases in a region and that specific diseases continue to be a challenge to manage, resulting in significant yield losses.
author:
  - name: Adam Sparks
    url: https://adamhsparks.netlify.app
date: 2022-02-03
output:
  distill::distill_article:
    self_contained: false
doi: "10.17605/OSF.IO/35JSY"
preview: Qld_APPS_Smith.jpg
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## About

Presenter: Dr. Linda Smith\
Institution: Crop and Food Science, Department of Agriculture and Fisheries, Queensland\
Host: Queensland Chapter Australasian Plant Pathology Society, [\@qldapps](https://twitter.com/qldapps)\
Date: February 3, 2022\
Links: [Video](https://youtu.be/tYwBIJY-A9Q)

## Biography

Dr Linda Smith is a Principal Plant Pathologist with the Queensland Department of Agriculture and Fisheries.
She has 15 years’ experience working on pathology issues in the cotton industry and over 30 years’ experience as a Plant Pathologist.
She leads and conducts research focussed on providing diagnostic capacity for fungal diseases and reniform nematode, conducting disease surveys to better understand disease issues and trends that direct pathology research, as well as development of management strategies for diseases and reniform nematode.
She leads a national project to better understand cotton diseases, soil health and management strategies that support the development of disease suppressive soils.

## Abstract

Cotton is susceptible to many yield-limiting diseases.
To understand the importance and impact of diseases present, disease surveys are conducted early and late season across all cotton growing regions to monitor the distribution and incidence of diseases.
The surveys also maintain the surveillance for exotic pathogens.
Surveys have been conducted in Queensland for 20 consecutive years.
Data provided by annual surveys have shown the relative importance of each of the diseases in a region and that specific diseases continue to be a challenge to manage, resulting in significant yield losses.
In addition to known endemic diseases we have identified several diseases of cotton for the first time, such as the defoliating pathotype of *Verticillium dahliae*, a pathogenic yeast *Eremothecium coryli* (originally *Nematospora coryli*) that causes seed and boll rot, the plant parasitic nematode *Rotylenchulus reniformis*, various leaf spot fungi, and a novel species of *Eutypella* causing a new wilt disease.
Although surveillance has provided long term data on the prevalence of diseases, it is the relationships that have been developed over time with growers, agronomists and REOs that have greatly assisted in these new detections.
This highlights how important it is for pathologists to have such a network to help keep in touch with what is happening in the field throughout the whole season.
