---
title: "Adaptation of a clonal pathogen - The story of Ascochyta rabiei in Australia"
description: |
  Ascochyta rabiei, a pathogenic fungus and the causing agent of Ascochyta blight of chickpea, is represented by a highly clonal population in Australia, due to the presence of only a single mating type. This presentation will summarise the current knowledge of the patterns and trends found in this unique population structure, as discovered by genetic analysis of isolates collected between 2013-2020 as part of ongoing monitoring studies led by Prof. Rebecca Ford at Griffith University.
author:
  - name: Adam Sparks
    url: https://adamhsparks.netlify.app
date: 2022-02-03
doi: "10.17605/OSF.IO/4N7ZD"
preview: Qld_APPS_Bar.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## About

Presenter: Dr. Ido Bar\
Institution: Centre for Planetary Health and Food Security, Griffith University\
Host: Queensland Chapter Australasian Plant Pathology Society, [\@qldapps](https://twitter.com/qldapps)\
Date: February 3, 2022\
Links: [Video](https://youtu.be/gD84BPDDEZM)

## Biography

Ido obtained his BSc (2007) and MSc (2011) in Israel with a focus on aquaculture genetics and breeding.
In 2012, he moved to Australia to continue in this field and take on a PhD candidature at the University of the Sunshine Coast in QLD, applying novel inter-species surrogate biotechnology to breed Southern Bluefin Tuna.
After his PhD, Ido took a postdoctoral position at Griffith University, which led to his current lecturer (Biosciences) and researcher position in affiliation with the Centre for Planetary Health and Food Security.
His research foci are crop genomics, crop-pathogen molecular interactions and development of novel pathogen diagnostics methods, which he investigates using molecular biology, genomics and bioinformatics approaches.
He aspires to develop applied research solutions in tight collaboration with the agriculture and aquaculture industries to overcome diseases and other production bottlenecks to help future food security.

## Abstract

*Ascochyta rabiei*, a pathogenic fungus and the causing agent of Ascochyta blight of chickpea, is represented by a highly clonal population in Australia, due to the presence of only a single mating type.
This presentation will summarise the current knowledge of the patterns and trends found in this unique population structure, as discovered by genetic analysis of isolates collected between 2013-2020 as part of ongoing monitoring studies led by Prof. Rebecca Ford at Griffith University.
The identified patterns suggest that *A. rabiei* displays micro-evolution in local regions, probably driven by founder effects, along with cross-regional gene flow, most likely due to anthropogenic activities.
