---
title: "Understanding plant-microbe- soil interactions to improve plant conservation and restoration outcomes"
description: |
  Although soil microbial communities, e.g., fungi and bacteria, are still largely considered a “black box”, their central role in ecosystem processes and function is indisputable. Despite the important role they play in carbon and nitrogen cycling, decomposition, and plant health there have been few attempts to incorporate soil microbial communities into conservation and restoration practice. In this talk, I will give an overview of my research pertaining plant- microbe interactions and how it has the potential to improve our understanding of plant-microbial dynamics in diverse ecosystems. Better understanding plant-microbial dynamics will also inform about the ecosystem-level processes and ecosystem health, e.g., decomposition rate, nutrient cycling, and plant nutrient acquisition. Finally, I will bring examples of our work that has practical applications for improving plant conservation and restoration outcomes.
author:
  - name: Adam Sparks
    url: https://adamhsparks.netlify.app
date: 2022-06-03
preview: "USQ-CCH_Birnbaum.jpg"
categories:
  - CCH-USQ Seminars
output:
  distill::distill_article:
    self_contained: false
doi: "DOI 10.17605/OSF.IO/FBJZY"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## About

Presenter: Dr. Christina Birnbaum\
Institution: Lecturer in Terrestrial Ecology at the University of Southern Queensland in Toowoomba, QLD\
Host: University of Southern Queensland Centre for Crop Health\
Date: June 3, 2022\
Links: [Video](https://youtu.be/6elBF_ParMU)

## Biography

Dr. Christina Birnbaum is a Lecturer in Terrestrial Ecology at the University of Southern Queensland in Toowoomba, QLD. Christina is an ecologist interested broadly in plant ecology and plant- microbe-soil interactions.
Christina uses field observations, combined with experimental manipulations and molecular tools to explore questions pertaining plant-microbe interactions in diverse ecosystems, including shrublands, saltmarshes, mangroves and peatlands, to inform invasive species management, restoration ecology and plant-microbial dynamics.
She serves on the Editorial Board of international peer-review journal Plant Ecology.
In 2016, Christina co- founded the inaugural Ecological Society of Australia Plant-Soil Ecology research chapter (RC), where she now serves as a lead- convener.
Christina joined USQ in 2022 where she now teaches into a variety of courses on ecology and the environment.
Her research continues to investigate the diversity of microbial communities in understudied ecosystems globally, their relationships with plants and effects on ecosystem properties and health.

## Abstract

Although soil microbial communities, e.g., fungi and bacteria, are still largely considered a "black box", their central role in ecosystem processes and function is indisputable.
Despite the important role they play in carbon and nitrogen cycling, decomposition, and plant health there have been few attempts to incorporate soil microbial communities into conservation and restoration practice.
In this talk, I will give an overview of my research pertaining plant- microbe interactions and how it has the potential to improve our understanding of plant-microbial dynamics in diverse ecosystems.
Better understanding plant-microbial dynamics will also inform about the ecosystem-level processes and ecosystem health, e.g., decomposition rate, nutrient cycling, and plant nutrient acquisition.
Finally, I will bring examples of our work that has practical applications for improving plant conservation and restoration outcomes.
