---
title: "Plant Rust Images: an open photo gallery of rusts from South Africa"
description: |
  This repository is a selection of images of rust diseases assembled by plant pathologists from the University of the Free State, Bloemfontein, South Africa. It is not intended to be a complete checklist of rust fungi in South Africa, but rather pictures of signs and symptoms of rusts studied or collected over several years.
author:
  - name: Emerson Del Ponte
    url: https://twitter.com/emdelponte
date: 2024-05-17
output:
  distill::distill_article:
    self_contained: false
preview: plantrust.png
categories:
  - Databases

---

## Background

Plant pathologists are excellent photographers but opportunities to share their images are often limited to articles, conferences and more recently social media. In most cases a wealth of exceptional photographs of plant diseases, and the organisms that cause them, remain buried on computers. In this project, the autrhos share rust pictures and hope that this resource will add to disease records and descriptions, visual diagnostics, teaching aids, etc. They hope the website inspires you take good pictures and capture your passion for plant pathology.

## What is this app for?

The shiny app allows for browsing the collection of plant rust images by rust genus and plant host, either by the scientific name or the common name. Thumbnails are shown and larger version of the image can be visualized by clicking on the thumbnail. It is also possible to download the high-quality images hosted in OSF Framework. 

## How was it developed?

The app was developed in R + Shiny and was made available at the shinyapps.io pages.

## Future plans

This project is open to contributions of images from the community.
Anyone interested in contributing should reach out to the authors

**Project website**: <https://epidemiologiaufv.shinyapps.io/plantrustimages/>\

