---
title: "Fusarium wilt of banana – an inevitable disease"
description: |
  Professor Elizabeth Aitken presents her group's work on Fusarium wilt, particularly on banana where host resistance, pathogen diversity and etiology are being explored for the Queensland Chapter of the Australasian Plant Pathology Society (APPS).
author:
  - name: Prof. Elizabeth Aitken
date: 07-15-2021
output:
  distill::distill_article:
    self_contained: false
preview: qld-apps-seminar-aitken.jpg
categories:
  - Qld-APPS Seminars
doi: "10.17605/OSF.IO/XGTQV"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## About

Presenter: Prof. Elizabeth Aitken \
Institution: The University of Queensland, School of Agriculture and Food Sciences \
Host: Queensland Chapter Australasian Plant Pathology Society, [\@qldapps](https://twitter.com/qldapps) \
Links: [Video](https://youtu.be/kbRoZublp1M)

## Biography

Professor Elizabeth Aitken has been an academic at UQ since 1993 lecturing plant pathology and fungal biology at undergraduate and postgraduate level.
Over that period much of her research has focused on diseases of tropical crops in particular banana, ginger, cotton and sunflower.
Research topics have included the genetics of plant-pathogen interactions, molecular aspects of pathogenicity and disease diagnostics.
Currently, her lab is concentrating on Fusarium wilt, particularly on banana where host resistance, pathogen diversity and etiology are being explored.
However, none of this work would have happened without the involvement of the numerous postgraduate and Honours students and postdocs, who have been in the Aitken lab over the years, as well as successful collaborations with colleagues.
Liz has also taken on significant committee roles in postgraduate student mentoring, biosafety and research integrity within the UQ community.
