---
title: "Establishing a community for supporting and fostering adoption of reproducible research using R"
description: |
  Lightning talk presented at useR!2018 in Brisbane, Queensland, Australia by Adam Sparks who discuss our methods of community building and what has worked and what has not for others that may wish to pursue similar efforts
author:
  - name: Adam Sparks
    url: https://twitter.com/adamhsparks
date: 07-13-2018
output:
  distill::distill_article:
    self_contained: false
preview: talk_opp1.png
categories:
  - Talks
---

[Slides](https://speakerdeck.com/adamhsparks/establishing-a-community-for-supporting-and-fostering-adoption-of-reproducible-research-using-r)

Talk given at [UseR!2018](https://user2018.r-project.org/")  
Bribane, Australia    
July 13, 2018

### Abstract
Botanical epidemiologists have long been leaders in adopting new and novel mathematical, statistical and computational approaches to address theoretical and applied research problems. As the availability of data increases at scales from genomes to landscapes, our approaches now require even more diverse skills to collaborate and advance the field. Reproducible research and open science practices are chief among these, however, relatively few examples in plant pathology exist. To support the adoption of these practices, we founded the Open Plant Pathology community (https://openplantpathology.org), which aims to foster relationships between researchers and promote open, transparent and reproducible research using shared data and reusable software, using R. I will discuss our methods of community building and what has worked and what has not for others that may wish to pursue similar efforts.

### References 

JJ Allaire, Yihui Xie, Jonathan McPherson, Javier Luraschi, Kevin Ushey, Aron Atkins, Hadley Wickham, Joe Cheng and Winston Chang (2018). rmarkdown: Dynamic Documents for R. R package version 1.10. https://CRAN.R-project.org/package=rmarkdown

Ben Marwick (2018). rrtools: Creates a reproducible research compendium. R package version 0.1.0. https://github.com/benmarwick/rrtools

RStudio Team (2016). RStudio: Integrated Development for R. RStudio, Inc., Boston, MA. http://www.rstudio.com/
Yihui Xie (2018). blogdown: Create Blogs and Websites with R Markdown. R package version 0.6.

Yihui Xie, Alison Presmanes Hill, and Amber Thomas (2017). blogdown: Creating Websites with R Markdown. Chapman and Hall/CRC. ISBN 978-0815363729

Hadley Wickham and Jay Hesselberth (2018). pkgdown: Make Static HTML Documentation for a Package. R package version 1.1.0. https://CRAN.R-project.org/package=pkgdown
