---
title: "Technology driven cassava pest management"
description: |
  In the recent past, a priority of many national research programs, international research institutions, non-governmental organizations, and funding agencies, has been focused on finding novel solutions to the complex constraints to cassava production. 
author:
  - name: Lisa Rothmann
date: 05-04-2020
output:
  distill::distill_article:
    self_contained: false
preview: seminar-cassava.jpg
categories:
  - Virtual Seminars
doi: "10.17605/OSF.IO/HR6SN"
---

### About

Presenter: Dr. Sally Mallowa\
Institution: Augustana University\
Date: May 4, 2020\
Host: Dr. Lisa Rothmann\
Links: [Video](https://youtu.be/1ND98xcPqkM) \| [Slides](https://doi.org/10.17605/OSF.IO/HR6SN)

## Abstract

Cassava is an important crop globally, however its importance as a food security crop, in Asia and Africa, its tolerance of a wider range of growth conditions and its increasing importance as a cash crop (_e.g._ for starch), cannot be over-emphasized.
In the recent past, a priority of many national research programs, international research institutions, non-governmental organizations, and funding agencies, has been focused on finding novel solutions to the complex constraints to cassava production.
There has been a measure of success on several fronts that integrate cutting edge technologies including sequencing for viral diseases, molecular breeding, disease monitoring and plant material tracking tools, use of AI in development of diagnostic apps amongst others.
There is great potential and promise in these tools, the boots on the ground are scientists in multi-institutional collaborations, ready to scale up and change things for farmers.
