---
title: "Deciphering the origin of powdery mildews in Australia. Implications for plant biosecurity"
description: |
  Seminar given by Dr. Levente Kiss (University of Southern Queensland). Powdery mildews are widespread obligate biotrophic fungal plant pathogens, comprising over 900 species that infect more than 10,000 plant species globally. The symptoms caused by these fungi are easy to spot, but the fungi themselves are difficult to handle, and some are difficult to identify. 
author:
  - name: Adam Sparks
    url: https://twitter.com/adamhsparks
date: 11-27-2020
output:
  distill::distill_article:
    self_contained: false
preview: seminar-levente.png
categories:
  - CCH-USQ Seminars
---

### Watch

[Slides](https://doi.org/10.17605/OSF.IO/THG7N) \| [Video](https://youtu.be/5rug_0Tr6Ew)

### Abstract

Seminar given by Dr. Levente Kiss (University of Southern Queensland). Powdery mildews are widespread obligate biotrophic fungal plant pathogens, comprising over 900 species that infect more than 10,000 plant species globally. The symptoms caused by these fungi are easy to spot, but the fungi themselves are difficult to handle, and some are difficult to identify. Many species cause economically important diseases of agricultural and horticultural crops; some have become invasive in different parts of the world, posing plant health biosecurity risks. In contrast to Eurasia and North America, powdery mildews are largely understudied in Australia. To address this knowledge gap in plant biosecurity diagnostics, a recent project produced an up-to-date list of all species that have been identified in Australia based on DNA barcode sequences. This was based on the precise identification of (i) specimens freshly collected from across the country; (ii) specimens preserved in plant pathology herbaria; and (iii) previously published DNA sequence data. The project confirmed the presence of 42 species in Australia. In Eurasia and North America, the number of powdery mildew species is much higher. Powdery mildew infections have been confirmed on only 13 native Australian plant species, and most of the causal agents were polyphagous that infect many other host plants both overseas and in Australia.

All powdery mildews infecting native plants in Australia were phylogenetically closely related to species known overseas. The data indicate that the Australian native vegetation may have evolved without being exposed to any powdery mildews until the 18th century, and most, if not all, species have been introduced since the European colonization of the continent. Powdery mildews are widespread obligate biotrophic fungal plant pathogens, comprising over 900 species that infect more than 10,000 plant species globally. The symptoms caused by these fungi are easy to spot, but the fungi themselves are difficult to handle, and some are difficult to identify. Many species cause economically important diseases of agricultural and horticultural crops; some have become invasive in different parts of the world, posing plant health biosecurity risks. In contrast to Eurasia and North America, powdery mildews are largely understudied in Australia. To address this knowledge gap in plant biosecurity diagnostics, a recent project produced an up-to-date list of all species that have been identified in Australia based on DNA barcode sequences.

This was based on the precise identification of (i) specimens freshly collected from across the country; (ii) specimens preserved in plant pathology herbaria; and (iii) previously published DNA sequence data. The project confirmed the presence of 42 species in Australia. In Eurasia and North America, the number of powdery mildew species is much higher. Powdery mildew infections have been confirmed on only 13 native Australian plant species, and most of the causal agents were polyphagous that infect many other host plants both overseas and in Australia. All powdery mildews infecting native plants in Australia were phylogenetically closely related to species known overseas. The data indicate that the Australian native vegetation may have evolved without being exposed to any powdery mildews until the 18th century, and most, if not all, species have been introduced since the European colonization of the continent.
