---
title: "Vanderplank: contributing an epidemic proportion to plant health"
description: |
  We are starting our #OPPtoons series with one of the famous plant pathologists responsible for providing the grounds for establishing the discipline of plant disease epidemiology, James Edward Vanderplank (VDP; 1908 - 1997).
author:
  - name: Lisa Rothmann
    url: https://twitter.com/LandbouLisa
  - name: Emerson Del Ponte
    url: https://twitter.com/edelponte
  - name: Fernando García-Bastidas
    url: https://twitter.com/Ferchucky
date: 03-15-2021
preview: vdp-preview.png
output:
  distill::distill_article:
    self_contained: false
bibliography: references.bib
categories: 
  - OPPToons
---

We are starting our #OPPtoons series with one of the famous plant pathologists responsible for providing the grounds for establishing the discipline of plant disease epidemiology, James Edward Vanderplank (VDP; 1908 - 1997).
His ideas and simple mathematical formulation on how plant diseases develop and spread over time were game-changing, unifying thoughts and arguing ecological principles for use in disease progress.
He set the groundwork for equipping plant pathologists with a toolbox for the analysis of epidemics and, as Vanderplank would say "set the strategy" for the control of plant diseases.

![Cartoon of JE Vanderplank teaching a class in muddy work clothes. Caption: JE Vanderplank (1908--1997), a "Boots on the ground" researcher, teaching and leading plant disease epidemiology from the front in a courteous and modest manner. His seminal and further ideas have definitely changed the face of plant pathology and breeding.](vdp-opptoon.jpg)

Born in the rural village of Eshowe, South Africa, VDP grew into a fond natural and agricultural scientist with academic training in botany, plant ecology and chemistry, taking his role in contributing to plant health seriously, and at an international level.
While leading the Division of Plant Protection (1958) and directing a newly formed Plant Protection Research Institute in South Africa (1962), VDP published his famous solo author book "Plant Diseases: Epidemics and Control" at the age of 55.
This fundamental manuscript was announced during the first International Epidemiology Workshop held in 1963, in France, a turning point for the formation of the studying plant disease epidemics.
Vanderplank wrote several book chapters and more solo author books in the following decades, even after retiring in 1973 [@coutinho2020].

Not only did VDP contribute written materials, but also to the potato breeding program and citrus post-harvest sanitation in South Africa.
Amongst his peers and students, he was considered a humble, "boots on the ground" researcher, teaching and leading from the front in a courteous and modest manner.
His seminal and further ideas have been supported and challenged by plant pathologists from his and future generations, but one thing remains in common - all express admiration for his work that definitely changed the face of plant pathology and breeding.
Together with his peers, VDP set the cornerstone of plant disease epidemiology, being crowned as a maverick, as the father of Plant Disease Epidemiology" [@zadoks1988] and the "founding father of modern quantitative [Botanical] Epidemiology" @thresh1998. In a world continually affected by epidemics and pandemics, we are glad to honour this giant whose shoulders have been a solid platform to build upon, with our first #OPPtoon.
