---
title: "Advances in understanding the host-mediated defence mechanism in wheat against rust infections"
description: |
  Sambasivam (Sam) Periyannan is a Scientist at the Agriculture and Food division of CSIRO and an Adjunct Associate Professor at the University of Queensland, Australia. After completing his PhD (Agriculture) at the University of Sydney in 2011, Sam started his scientific career as a postdoctoral fellow (2011-2016) at CSIRO, where he eventually became an independent scientist in 2016. Between 2017-2019, Sam took a secondment position at the Australian National University (ANU) to complete his ARC DECRA project. He also served as the “Crop Resistance Genes” team leader at CSIRO from 2019 to 2021. Sam’s research interest is centred on molecular genetics and pathology, focusing on cereal crops and rust pathogens. Apart from publications in top journals such as Science and Nature Biotechnology, Sam is the recipient of prestigious awards such as the Goldacre award from the Australian Society of Plant Scientists and Chairman’s Medal from CSIRO. Currently he is a Senior Editor for Plant Disease and Associate Editor for BMC Biology and Frontiers in Plant Science.
author:
  - name: Adam Sparks
    url: https://adamhsparks.netlify.app
date: 2022-04-22
preview: USQ-CCH_Periyannan.png
categories:
  - CCH-USQ Seminars
output:
  distill::distill_article:
    self_contained: false
doi: "10.17605/OSF.IO/DUMXP"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## About

Presenter: Dr. Sambasavam Periyannan\
Institution: CSIRO and University of Queensland\
Date: April 22, 2022\
Time: 10:00AM - 11:00PM AEST\
Host: USQ CCH\
Links: [Video](https://youtu.be/qABaqIeoKIM)

## Abstract

Rust fungi belonging to the genus *Puccinia* have an important impact on wheat cultivation and human food security worldwide.
Routinely rust infections are managed through the effective use of genetic resistance, an innate ability in plants to resist pests and pathogens.
While the modern wheat cultivars are prone to attack by the recently evolved rust strains, the historical collection of domesticated wheat and its wild relatives are resilient due to enriched genetic diversity.
We mapped, identified, and characterised a few rust resistance genes from wheat and its progenitor and wild relatives through map-based cloning.
However, due to the large and complex nature of the wheat genome, this conventional process is tedious and time-consuming.
But with the near-complete sequencing of the wheat genome and advancements in DNA capture and sequencing, we have developed robust strategies to accelerate resistance gene cloning.
Further, through gene cassette technology, we combined and introduced multiple and diverse rust resistance genes in a common wheat cultivar.
In parallel, we have made progress in accelerating rust pathogen surveillance through effective integration of DNA sequencing techniques that will ensure precise selection of resistance genes to protect wheat from the newly emerged rust strains.
